### ISSUE TITLE
Doubt regarding use of other datasets

### ISSUE THREAD

**Issue by rayruchira** [khanhnamle1994/transfer-rec#3]
Hi there, 
I wanted to run the **CDAE, ESAE** and **SVAE** models for other datasets ( **Movielens 20M/10M /Netflix /custom datset having UserId, ItemId, rating**). 

Could you guide me regarding the data preprocessing and the directory set up? 
Is there a .py file that does the mentioned ? If, yes what changes do I have to make and how do I go forward with it ?

Thanks in advance!

**Comment by khanhnamle1994** [comment]
@rayruchira I would say taking a look at the corresponding papers that implement those models. They usually include details about their experimental settings, which certainly have data pre-processing information.
